# Generated by Django 4.1 on 2023-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EbayProductInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ebay_item_id", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=3, max_digits=10)),
                ("price_currency", models.CharField(max_length=10)),
                ("condition", models.CharField(max_length=50)),
                ("listing_market_place_ebay_id", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "ebay_product_information",
            },
        ),
    ]
