# Generated by Django 4.1 on 2023-06-23 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserProductAlertsConfiguration",
            new_name="UserProductSearchPhrases",
        ),
        migrations.AlterModelTable(
            name="userproductsearchphrases",
            table="user_product_search_phrases",
        ),
    ]
