# Generated by Django 4.1 on 2023-06-23 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0002_rename_userproductalertsconfiguration_userproductsearchphrases_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userproductsearchphrases",
            old_name="user_id",
            new_name="user",
        ),
    ]
